// Observe the request generated by ChatGPT's own Delete UI. Never call its account API.
use serde_json::Value;
use std::collections::BTreeMap;

pub(crate) struct Watch {
    chat: String,
    requests: BTreeMap<String, (u16, bool)>,
}

impl Watch {
    pub fn new(expected: &str) -> Self {
        let url = url::Url::parse(expected).expect("validated conversation URL");
        Self {
            chat: url.path().rsplit('/').next().unwrap().into(),
            requests: BTreeMap::new(),
        }
    }

    fn target(&self, value: &str) -> bool {
        super::valid_chat_url(value)
            && url::Url::parse(value).is_ok_and(|url| {
                url.path() == format!("/backend-api/conversation/{}", self.chat)
                    || url.path() == format!("/backend-api/conversation/id/{}", self.chat)
            })
    }

    pub fn event(&mut self, event: &Value) {
        let params = &event["params"];
        let Some(id) = params["requestId"].as_str() else {
            return;
        };
        match event["method"].as_str().unwrap_or_default() {
            "Network.requestWillBeSent" => {
                // A redirect must not inherit a previously matched request's authority.
                self.requests.remove(id);
                let request = &params["request"];
                let deletion = request["method"] == "DELETE"
                    || request["method"] == "PATCH"
                        && request["postData"]
                            .as_str()
                            .and_then(|body| serde_json::from_str::<Value>(body).ok())
                            .is_some_and(|body| body["is_visible"] == false);
                if deletion
                    && request["url"].as_str().is_some_and(|url| self.target(url))
                    && self.requests.len() < 16
                {
                    self.requests.insert(id.into(), (0, false));
                }
            }
            "Network.responseReceived" => {
                if !params["response"]["url"]
                    .as_str()
                    .is_some_and(|url| self.target(url))
                {
                    self.requests.remove(id);
                } else if let Some(request) = self.requests.get_mut(id) {
                    request.0 = params["response"]["status"].as_u64().unwrap_or_default() as u16;
                }
            }
            "Network.loadingFinished" => {
                if let Some(request) = self.requests.get_mut(id) {
                    request.1 = true;
                }
            }
            "Network.loadingFailed" => {
                self.requests.remove(id);
            }
            _ => {}
        }
    }

    pub fn ready(&self) -> Vec<(String, u16)> {
        self.requests
            .iter()
            .filter(|(_, (_, finished))| *finished)
            .map(|(id, (status, _))| (id.clone(), *status))
            .collect()
    }

    pub fn consume(&mut self, id: &str) {
        self.requests.remove(id);
    }

    pub fn acknowledged(&self, status: u16, body: &Value) -> bool {
        (200..300).contains(&status)
            && (status == 204
                || body["success"] == true
                    && body.get("id").is_none_or(|id| *id == self.chat)
                    && body
                        .get("is_visible")
                        .is_none_or(|visible| *visible == false)
                || body["id"] == self.chat && body["is_visible"] == false)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn deletion_receipts_require_exact_ui_request_success_and_acknowledgement() {
        let mut watch = Watch::new("https://chatgpt.com/c/ours");
        let request = |url: &str, method: &str, data: &str| json!({"method":"Network.requestWillBeSent","params":{"requestId":"one","request":{"url":url,"method":method,"postData":data}}});
        let owned = "https://chatgpt.com/backend-api/conversation/ours";
        for (url, method, body) in [
            (owned, "GET", ""),
            (owned, "PATCH", "{}"),
            (owned, "PATCH", "{\"is_visible\":true}"),
            (
                "https://chatgpt.com/backend-api/conversation/other",
                "PATCH",
                "{\"is_visible\":false}",
            ),
            (
                "https://chatgpt.com.evil.test/backend-api/conversation/ours",
                "DELETE",
                "",
            ),
        ] {
            watch.event(&request(url, method, body));
            assert!(watch.requests.is_empty());
        }
        watch.event(&request(owned, "PATCH", "{\"is_visible\":false}"));
        watch.event(&json!({"method":"Network.responseReceived","params":{"requestId":"one","response":{"url":owned,"status":200}}}));
        assert!(watch.ready().is_empty());
        watch.event(&json!({"method":"Network.loadingFinished","params":{"requestId":"one"}}));
        assert_eq!(watch.ready(), vec![("one".into(), 200)]);
        assert!(watch.acknowledged(200, &json!({"success":true})));
        assert!(watch.acknowledged(200, &json!({"id":"ours","is_visible":false})));
        assert!(watch.acknowledged(204, &Value::Null));
        let current = "https://chatgpt.com/backend-api/conversation/id/ours";
        watch.event(&request(current, "DELETE", ""));
        watch.event(&json!({"method":"Network.responseReceived","params":{"requestId":"one","response":{"url":current,"status":200}}}));
        watch.event(&json!({"method":"Network.loadingFinished","params":{"requestId":"one"}}));
        assert_eq!(watch.ready(), vec![("one".into(), 200)]);
        for (status, body) in [
            (403, json!({"success":true})),
            (404, json!({"detail":"not found"})),
            (500, json!({"success":true})),
            (200, json!({"success":false})),
            (200, json!({})),
            (200, json!({"id":"other","is_visible":false})),
            (200, json!({"success":true,"id":"other"})),
            (200, json!({"success":true,"is_visible":true})),
        ] {
            assert!(!watch.acknowledged(status, &body));
        }
        watch.event(&request("https://chatgpt.com/", "GET", ""));
        assert!(watch.ready().is_empty()); // same request ID redirected elsewhere
    }
}
